project_id = "brumbzbtvqkslzhlpsxh"

[functions.analyze-sentiment]
verify_jwt = false

[functions.analyze-ticket]
verify_jwt = false

[functions.send-ticket-notification]
verify_jwt = false

[functions.momence-api]
verify_jwt = false
